# Generated by Django 4.2.2 on 2023-06-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_empleo_user_empleado_user_empresa_delete_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_empresa',
            name='edad',
        ),
        migrations.AddField(
            model_name='user_empresa',
            name='contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_empresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleo',
            name='empresa',
            field=models.CharField(max_length=30),
        ),
    ]
